### ISSUE TITLE
Using COMPUTE_MAXS ERROR Helper

### ISSUE THREAD

**Issue by nguyenvanthinhdev** [java-deobfuscator/deobfuscator-gui#60]
[Thread-2] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: javax/microedition/lcdui/Graphics could not be found while writing aM. Using COMPUTE_MAXS
Error: javax/microedition/lcdui/Displayable could not be found while writing cA. Using COMPUTE_MAXS
Error: javax/microedition/io/HttpConnection could not be found while writing ce. Using COMPUTE_MAXS
Error: javax/microedition/lcdui/Graphics could not be found while writing p. Using COMPUTE_MAXS
Error: javax/microedition/rms/RecordStore could not be found while writing eV. Using COMPUTE_MAXS
Error: javax/microedition/lcdui/Graphics could not be found while writing fB. Using COMPUTE_MAXS
Error: javax/microedition/rms/RecordStore could not be found while writing ee. Using COMPUTE_MAXS
Error: javax/microedition/io/HttpConnection could not be found while writing fN. Using COMPUTE_MAXS
Error: javax/microedition/lcdui/Displayable could not be found while writing ey. Using COMPUTE_MAXS

and

deobfuscation failed. please open a ticket on GitHub and provide the following error

![Screenshot 2022-09-16 212830](https://user-images.githubusercontent.com/107993570/190836898-e5b706c7-3c33-4b05-bdfc-6d19e7b42851.png)

**Comment by Janmm14** [comment]
You are missing library/path jars (atm they're identically handled by the deobfuscator), thats why it falls back to COMPUTE_MAXS usage.

The error is probably happening because somehow you started the deobfuscation again while the previous run was still ongoing.

SmartRedo is useless, as it is related to transformers and you didn't choose any.
Also DebugRulesAnalyzer is not doing anything because you are not usingthe detect feature.
The checkboxes are extracted from the deobfuscators yaml configuration, that is why the GUI is not hinting at these things.

When in doubt, disable delete useless classes as well.

**Comment by Janmm14** [comment]
No reply, closing until @nguyenvanthinhdev replies
