### ISSUE TITLE
claiming weird stuff, not really an issue (orig title: ip grabber)

### ISSUE THREAD

**Issue by AquaNot** [java-deobfuscator/deobfuscator-gui#64]
doxxer

**Comment by Janmm14** [comment]
I think one of the following possibilities happenend:

- you are misunderstanding something
- you commented at the wrong place
- you are lacking proper knowledge and assumed too much
- you had downloaded some sophisticated malware usually hiding in mc plugins which can infect all kinds of jar files even outside server plugins
- you are angry because idk

I am 100% certain that neither the gui nor the actual deobfuscator project contain (neither now nor in the past) any code suitable for ip grabbing.
Therefore I am closing this issue.

If your opinion is still different and its not just your emotions, provide details and I'd be happy to help and remove any kind of security hole from this software.
